### ISSUE TITLE
Settings for ogbn-arxiv

### ISSUE THREAD

**Issue by jumxglhf** [nerdslab/bgrl#3]
Dear authors, 

Thanks for open-sourcing the code. I'm wondering what're the settings to reproduce results reported in the paper?

**Comment by hcmdgh** [comment]
Faced the same problem.

**Comment by jumxglhf** [comment]
I successfully reproduced the results by using the hyper-parameters described in the appendix of the original paper. It seems like the normalizations (batch vs layer) are quite important. After switching to the correct normalization on ogbn-arxiv the results are reproduced.
